### ISSUE TITLE
能否支持下划线驼峰互转的传参与返回

### ISSUE THREAD

**Issue by zxyfaxcn** [tw2066/api-docs#10]
有些时候后端接口对外定义的传参/返回都是下划线命名风格，但是类成员变量通常是推荐驼峰命名方式的，那么必然就存在一个传参下换线，转换成驼峰的场景；以及在返回时，将驼峰命名的转换成下划线

**Comment by tw2066** [comment]
https://github.com/tw2066/dto/commit/2f0e71e7fe32c1a96e531db1ce414fb4154aff19

**Comment by zxyfaxcn** [comment]
感谢回复

目前测试下来的情况是：
1 request 实际请求的时候是可以的，添加JSONField后会处理到别名的参数接收、规则验证
2 回包添加了JSONField 暂还没有生效
3 文档中添加JSONField的对应字段描述暂时还不是别名
