### ISSUE TITLE
数组字段验证

### ISSUE THREAD

**Issue by wjycoder** [tw2066/api-docs#13]
可否增加对数组字段的规则验证功能，如下验证field1 和field2

```json
{
  "info": [
    {
      "field1": 1,
      "field2": "string"
    },
    {
      "field1": 2,
      "field2": "string2"
    }
  ]
}
```

**Comment by xu767142206** [comment]
> 可否增加对数组字段的规则验证功能，如下验证field1 和field2
> 
> ```json
> {
>   "info": [
>     {
>       "field1": 1,
>       "field2": "string"
>     },
>     {
>       "field1": 2,
>       "field2": "string2"
>     }
>   ]
> }
> ```

你其实可以自定义一个Annotation 然后监听AfterDtoStart事件 去获取你自定义的注解 加入至rule列表就行了 我这只是简单的实现 你可以参考下 
![image](https://user-images.githubusercontent.com/44433417/216620361-ddd3e01a-5b87-4d22-bd58-1f5ed100c325.png)

**Comment by tw2066** [comment]
验证数组的注解 `#[Arr]`


`{ "field1": 1,"field2": "string"}` 理解为一个对象 如:`\App\DTO\Address`


----------------------------------
参考
```php
    /**
     * 映射数组.
     * @var \App\DTO\Address[]
     */
    #[ApiModelProperty('地址')]
    public array $addressArr;
```

**Comment by tw2066** [comment]
@xu767142206 
要使用自定义验证注解, 有简单的方法
> rule 支持框架所有验证
- 自定义验证注解
> 只需继承`Hyperf\DTO\Annotation\Validation\BaseValidation`即可
```php
#[Attribute(Attribute::TARGET_PROPERTY)]
class Image extends BaseValidation
{
    protected $rule = 'image';
}
```

**Comment by LazySleep** [comment]
> 验证数组的注解 `#[Arr]`
> 
> `{ "field1": 1,"field2": "string"}` 理解为一个对象 如:`\App\DTO\Address`
> 
> 参考
> 
> ```
>     /**
>      * 映射数组.
>      * @var \App\DTO\Address[]
>      */
>     #[ApiModelProperty('地址')]
>     public array $addressArr;
> ```

没有验证到数组
