### ISSUE TITLE
定义的DTO没有在Controller中的入参和回参声明使用到就会报错

### ISSUE THREAD

**Issue by huangshunyang** [tw2066/api-docs#14]
![image](https://user-images.githubusercontent.com/43840410/216582984-9286f91b-8ebb-419f-a70f-b372de99570f.png)

**Comment by tw2066** [comment]
提供一下可复现的代码

**Comment by huangshunyang** [comment]
复现代码以及步骤如下：


1.如下所示，我定义了一个TestDTO，并使用ApiModel注解标记这个DTO，并使用ApiModelProperty标记其中的成员属性
-------------------------DTO代码开始-------------------------------
namespace App\DTO;
use Hyperf\ApiDocs\Annotation\ApiModel;
use Hyperf\ApiDocs\Annotation\ApiModelProperty;

#[ApiModel("这是一个测试的DTO")]
class TestDTO
{
    #[ApiModelProperty("测试名称")]
    public string $name;
}
--------------------------DTO代码结束------------------------------




2.如下所示，我接着定义了一个Controller，其中声明了一个testApi的方法，该方法的参数中使用到了步骤1定义的TestDTO，此时启动框架没有任何问题，一切正常
------------------------Controller代码开始------------------------------- 
namespace App\Controller;
use App\DTO\TestDTO;
use Hyperf\ApiDocs\Annotation\Api;
use Hyperf\HttpServer\Annotation\Controller;
use Hyperf\HttpServer\Annotation\GetMapping;

#[Api("测试控制器")]
#[Controller(prefix: "test")]
class TestController
{
    #[GetMapping(path: "testApi")]
    public function testApi(TestDTO $DTO): string  // 注意，这一行的控制器代码使用到了TestDTO，所以不会报错
    {
        return "hello world";
    }
}
--------------------------Controller代码结束------------------------------




3.如果我把TestController控制器的代码稍微改一下，就会复现
------------------------Controller代码开始------------------------------- 
namespace App\Controller;
use App\DTO\TestDTO;
use Hyperf\ApiDocs\Annotation\Api;
use Hyperf\HttpServer\Annotation\Controller;
use Hyperf\HttpServer\Annotation\GetMapping;

#[Api("测试控制器")]
#[Controller(prefix: "test")]
class TestController
{
    #[GetMapping(path: "testApi")]
    public function testApi(/*TestDTO $DTO*/): string   // 注意：该行将原来的   testApi(TestDTO $DTO)   改成了 testApi(/*TestDTO $DTO*/)
    {
        return "hello world";
    }
}
--------------------------Controller代码结束------------------------------


以上代码将TestDTO在控制器中的声明注释掉了，相当于被@ApiModel注解修饰的TestDTO类没有被任何一个控制器使用到，此时启动框架就会复现之前截图上的报错

**Comment by tw2066** [comment]
https://github.com/tw2066/api-docs/commit/23260516504a653ae668cf889a2731f1b6aa4fb7

原因:收集了无效的ApiModel, 导致DTO里没有对应的数据

composer update
