### ISSUE TITLE
请教如何设置自定义返回内容？

### ISSUE THREAD

**Issue by jenawant** [tw2066/api-docs#19]
比如登录场景下，成功后只返回token，并不需要在DTO里定义，该如何写注解呢？谢谢

**Comment by tw2066** [comment]
```
    #[ApiOperation('登录2', security: false)]
    #[PostMapping(path: 'login2')]
    public function login2(#[RequestBody] #[Valid] DemoBodyRequest $request): string
    {
        //todo
        $token = '123';
        return $token;
    }
```

**Comment by jenawant** [comment]
感谢回复，应该是我表达的不清晰，继续请教：
在hyperf里，典型应用场景是每个控制器定义一个公共验证器，控制器里的方法都使用该验证器，返回是ResponseInterface对象，示例代码如下

    #[PostMapping("login")]
    #[ApiOperation(summary: 'User Login')]
    #[ApiHeader(name: 'X-Client', required: true, type: 'string', description: 'The flag for request client')]
    #[ApiFormData(name: 'username', required: true, type: 'string', description: 'The user account IN email format')]
    #[ApiFormData(name: 'password', required: true, type: 'string', description: 'The account Password')]
    #[ApiResponse(response: '200', description: 'Success, and return token')]
    public function login(SystemUserRequest $request): ResponseInterface
    {
        $requestData = $request->validated();
        return $this->success(['token' => $this->userService->login($requestData)]);
    }

最终响应给终端的结构是 
{
   success: true,
   code:200,
   message:'成功',
   data:{token:'xxxxxxxxxxxxxxxxxx'}
}

所以：
1，像这种场景，如何定义ApiResponse？
2，多个方法共用SystemUserRequest验证器，而且验证器还会继承多层父类，每个父类都有属性，父类有可能是在vendor里，也不能使用注释#[ApiModelProperty]隐藏，那如何使用注解#[RequestBody]获取到该方法的参数？目前我是用注解#[ApiFormData]手写
3，GET方法，注解#[RequestQuery]也是同第2点一样的问题，也不能正确获取参数，关键是还没有可用注解，不能手写

讨论：
1，是否可以增加ApiParameter注解，支持自定义配置 in 类型，这样就可以比较灵活的设置parameters，header也可以，query也可以，同时ApiHeader就可以精简掉了
2，是否可以扩展ApiResponse，支持自定义配置返回结构体

感谢。如有理解不正确的，还请指正。

**Comment by zxyfaxcn** [comment]
好问题，关于讨论中的Response，你是希望实现类似 Java中泛型定义、识别吗？目前 PHP 好像不太好实现，得想想看有没有其它方式。

**Comment by jenawant** [comment]
草率了，致歉
整明白了，致敬
