### ISSUE TITLE
验证器能不能将 ApiModelProperty 里面的 替换 验证字段， 并且 这个值支持多语言

### ISSUE THREAD

**Issue by ice-leng** [tw2066/api-docs#2]
验证器能不能将 ApiModelProperty 里面的 替换 验证字段， 并且 这个值支持多语言
<img width="596" alt="image" src="https://user-images.githubusercontent.com/7506787/154287564-509e8f08-bf6a-4bd5-a131-46ad7f606645.png">

**Comment by tw2066** [comment]
已替换 支持
