### ISSUE TITLE
为什么我生成的文档不可以测试。

### ISSUE THREAD

**Issue by miwei230** [tw2066/api-docs#24]
我生成的文档里，不能在表单中输入参数。
也没有按钮去点击测试链接。 
都是这样子的吗？还是说我设置错了。
![image](https://github.com/tw2066/api-docs/assets/20872930/20e2e721-2af1-4356-9b87-5ea57a5473a9)

**Comment by tw2066** [comment]
点击右上角的 `Try it out`
