### ISSUE TITLE
RequestQuery RequestBody 被标记成已经弃用 Deprecated

### ISSUE THREAD

**Issue by FireSoil** [tw2066/api-docs#28]
RequestQuery RequestBody 被标记成已经弃用 Deprecated
hyperf/framework 3.0.23
![WX20230905-120556@2x](https://github.com/tw2066/api-docs/assets/12509091/62cf7880-921a-482f-b833-f03331389291)

**Comment by FireSoil** [comment]
补充 tangwei/apidocs v3.0.0-beta3

**Comment by tw2066** [comment]
已修复 https://github.com/tw2066/dto/commit/119a9bc3705d2c2d05b007cd33e62b20c9d24953
