### ISSUE TITLE
在API自动化测试中DTO的属性值不会自动填充，但是启动Hyperf后用Swagger文档测试是OK的

### ISSUE THREAD

**Issue by SparkLee** [tw2066/api-docs#29]
use HyperfTest\HttpTestCase;

class ExampleTest extends HttpTestCase
{
    public function test_example()
    {
        $this->json('/', ['foo' => 'bar'])
    }
}

**Comment by SparkLee** [comment]
我暂时的解决方案是在自动化测试启动文件（test\bootstrap.php）中加入如下这么一行代码就行了：

// 本项目依赖 composer 扩展 "tangwei/dto" 将 http 请求参数自动转化为 Controller 方法中的 DTO 参数对象。而 "tangwei/dto" 是通过监听 Hyperf\Framework\Event\BeforeServerStart 和
// Hyperf\Server\Event\MainCoroutineServerStart 这两个事件（参见：Hyperf\DTO\BeforeServerListener::listen()）来插入 DTO 自动转化逻辑代码的，但是在执行 phpunit 单元测试的流程中这
// 两个事件貌似都没有被触发，为了让 DTO 自动转化机制生效，故在此处手动触发一下 BeforeServerStart 事件。
$container->get(Psr\EventDispatcher\EventDispatcherInterface::class)->dispatch(new Hyperf\Framework\Event\BeforeServerStart('http'));

**Comment by SparkLee** [comment]
@tw2066 是不是可以考虑在 Hyperf\DTO\BeforeServerListener::listen() 中再监听一个专用的事件，然后在有需要的地方（比如 phpunit 自动化测试的启动文件 test\bootstrap.php 中）手动触发这个事件，从而激活 DTO 对象自动转化的逻辑。

**Comment by tw2066** [comment]
https://github.com/tw2066/dto/commit/44d09678785b58edbe6411812bf75ae0999f0257
