### ISSUE TITLE
php8.2 hyperf里使用报错

### ISSUE THREAD

**Issue by ShrRung** [tw2066/api-docs#30]
PHP 版本：       8.2
hyperf版本：    3.0.45
swoole 版本：  5.0.3
api-docs版本：2.1.12
报错如下：
        Narrowing occurred during type inference of ZEND_FETCH_DIM_W. Please file a bug report on https://github.com/php/php-src/issues in ./vendor/tangwei/apidocs/src/Swagger/SwaggerOpenApi.php

**Comment by ShrRung** [comment]
https://github.com/php/php-src/issues/12927  8.2.14解决了

**Comment by tw2066** [comment]
ok
