### ISSUE TITLE
api_docs修改enable启动后

### ISSUE THREAD

**Issue by xu767142206** [tw2066/api-docs#5]
修改了此配置后
return [
    // enable false 将不会启动 swagger 服务
    'enable' => false,
    'format' => 'json',
   ...
];
修改了以上配置 然后启动就报错了

报错：
Fatal error: Uncaught Error: Typed static property Hyperf\ApiDocs\Listener\BootAppRouteListener::$massage must not be accessed before initialization in /cygdrive/f/xycphp/php8/lsk-

**Comment by xu767142206** [comment]
![image](https://user-images.githubusercontent.com/44433417/202428358-381e01f3-56aa-4af9-a6ee-9af65bee3d41.png)

**Comment by xu767142206** [comment]
### 解决 我在AfterWorkerStartListener中加了一行 CoordinatorManager::until(Constants::WORKER_START)->yield(); 代码后解决 希望大神帮忙解惑下 是我环境问题嘛

**Comment by tw2066** [comment]
已修复,   composer update
