### ISSUE TITLE
能否支持多模块拆分文档

### ISSUE THREAD

**Issue by LazySleep** [tw2066/api-docs#7]
项目文档都放在单个文档中使得文档过于庞大

能否在Api注解上增加模块名以生成不同的swagger配置文件（如果没有更优的方案的话）

实现下图的效果
![image](https://user-images.githubusercontent.com/32838949/205436638-7247b0ba-f285-4528-9838-28bbbb58d7be.png)

需要在swagger-ui中配置urls
![image](https://user-images.githubusercontent.com/32838949/205436555-30853583-0c90-41ad-a788-9aa65928c28e.png)

感谢🙏

**Comment by tw2066** [comment]
优先级较低, 暂时不考虑
